In [ ]:
import pandas as pd

In [ ]:
pd.set_option('display.max_colwidth', None) # to increase the width of the columns

In [ ]:
# orders.csv
url = "https://drive.google.com/file/d/1Vu0q91qZw6lqhIqbjoXYvYAQTmVHh6uZ/view?usp=sharing"
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
orders = pd.read_csv(path)

# orderlines.csv
url = "https://drive.google.com/file/d/1FYhN_2AzTBFuWcfHaRuKcuCE6CWXsWtG/view?usp=sharing"
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
orderlines = pd.read_csv(path)

Before we begin, let's create a copy of the `orders` and `orderlines` DataFrames. This way we are sure any of our changes won't affect the original DataFrames.

In [ ]:
orders_df = orders.copy()

In [ ]:
orderlines_df = orderlines.copy()

## 1.&nbsp; Duplicates

In [ ]:
# orders
orders_df.duplicated().sum()

np.int64(0)

In [ ]:
# orderlines
orderlines_df.duplicated().sum()

np.int64(0)

# 2.&nbsp; `.info()`

In [ ]:
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226909 entries, 0 to 226908
Data columns (total 4 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   order_id      226909 non-null  int64
 1   created_date  226909 non-null  object
 2   total_paid    226904 non-null  float64
 3   state         226909 non-null  object
dtypes: float64(1), int64(1), object(2)
memory usage: 6.9+ MB

In [ ]:
orderlines_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 293983 entries, 0 to 293982
Data columns (total 7 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                293983 non-null  int64
 1   id_order          293983 non-null  int64
 2   product_id        293983 non-null  int64
 3   product_quantity  293983 non-null  int64
 4   sku               293983 non-null  object
 5   unit_price        293983 non-null  object
 6   date              293983 non-null  object
dtypes: int64(4), object(3)
memory usage: 15.7+ MB

* `date` should be a datetime datatype
* `unit_price` should be a float datatype

## 3.&nbsp; Missing values

### 3.1.&nbsp; Orders
* `total_paid` has 5 missing values

In [ ]:
print(f"5 missing values represents {((orders_df.total_paid.isna().sum() / orders_df.shape[0])*100).round(5)}% of the rows in our DataFrame")

5 missing values represents 0.0022% of the rows in our DataFrame

In [ ]:
orders_df.total_paid.isna().value_counts(normalize=True)

total_paid
False    0.999978
True     0.000022
Name: proportion, dtype: float64

As there is such a tiny amount of missing values, we will simply delete these rows, as we have enough data without them.

In [ ]:
orders_df = orders_df.loc[~orders.total_paid.isna(), :]

### 3.2.&nbsp; Orderlines
There are no missing values in `orderlines`

## 4.&nbsp; Datatypes

### 4.1.&nbsp; Orders
* `created_date` should become datetime datatype

In [ ]:
orders_df["created_date"] = pd.to_datetime(orders_df["created_date"])

### 4.1.&nbsp; Orderlines

In [ ]:
orderlines_df["date"] = pd.to_datetime(orderlines_df["date"])

#### 4.1.2.&nbsp;`unit_price`

In [ ]:
orderlines_df.unit_price.str.contains(r"\d+\.\d+\.\d+").value_counts()

unit_price
False    257814
True      36169
Name: count, dtype: int64

Looks like over 36000 rows in `orderlines` are affected by this problem. Let's work out how much that is as a percentage of our total data.

In [ ]:
two_dot_percentage = ((orderlines_df.unit_price.str.contains(r"\d+\.\d+\.\d+").value_counts().iloc[1] / orderlines_df.shape[0])*100).round(2)
print(f"The 2 dot problem represents {two_dot_percentage}% of the rows in our DataFrame")

The 2 dot problem represents 12.3% of the rows in our DataFrame

In [ ]:
two_dot_order_ids_list = orderlines_df.loc[orderlines_df.unit_price.str.contains(r"\d+\.\d+\.\d+"), "id_order"]

orderlines_df = orderlines_df.loc[~orderlines_df.id_order.isin(two_dot_order_ids_list)]

In [ ]:
orderlines_df.shape[0]

216250

We still have 216250 rows in orderlines to work with. This should be more than enough for our evaluation.

Now that all of the 2 decimal point prices have been removed, let's try again to convert the column `unit_price` to the correct datatype.

In [ ]:
orderlines_df["unit_price"] = pd.to_numeric(orderlines_df["unit_price"])

It worked perfectly

In [ ]:
# products.csv
url = "https://drive.google.com/file/d/1afxwDXfl-7cQ_qLwyDitfcCx3u7WMvkU/view?usp=sharing"
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
products = pd.read_csv(path)

In [ ]:
products_df = products.copy()

In [ ]:
products_df.head()

,sku,name,desc,price,promo_price,in_stock,type
0,RAI0007,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,499.899,1,8696
1,APP0023,Apple Mac Keyboard Keypad Spanish,USB ultrathin keyboard Apple Mac Spanish.,59,589.996,0,13855401
2,APP0025,Mighty Mouse Apple Mouse for Mac,mouse Apple USB cable.,59,569.898,0,1387
3,APP0072,Apple Dock to USB Cable iPhone and iPod white,IPhone dock and USB Cable Apple iPod.,25,229.997,0,1230
4,KIN0007,Mac Memory Kingston 2GB 667MHz DDR2 SO-DIMM,2GB RAM Mac mini and iMac (2006/07) MacBook Pro (2006/07/08).,34.99,31.99,1,1364

In [ ]:
products_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19326 entries, 0 to 19325
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sku          19326 non-null  object
 1   name         19326 non-null  object
 2   desc         19319 non-null  object
 3   price        19280 non-null  object
 4   promo_price  19326 non-null  object
 5   in_stock     19326 non-null  int64
 6   type         19276 non-null  object
dtypes: int64(1), object(6)
memory usage: 1.0+ MB

We'll go through the steps above in order
* Duplicates
* Missing values
* Datatypes

But I think we can all see straight away from `products.head()` above that some of the prices in `promo_price` look wrong. Let's make sure we deal with this later.

## Duplicates

In [ ]:
products_df.duplicated().sum()

np.int64(8746)

In [ ]:
products_df = products_df.drop_duplicates()

## `.info()`

In [ ]:
products_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10580 entries, 0 to 19325
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sku          10580 non-null  object
 1   name         10580 non-null  object
 2   desc         10573 non-null  object
 3   price        10534 non-null  object
 4   promo_price  10580 non-null  object
 5   in_stock     10580 non-null  int64
 6   type         10530 non-null  object
dtypes: int64(1), object(6)
memory usage: 661.2+ KB

### Missing values
We can see from `.info()` above that we have missing values in `desc` and `price`

#### `desc`

In [ ]:
products_df["desc"].isna().sum()

np.int64(7)

In [ ]:
products_df.loc[products_df['desc'].isna(), :]

,sku,name,desc,price,promo_price,in_stock,type
16126,WDT0211-A,"Open - Purple 2TB WD 35 ""PC Security Mac hard drive and NAS",NaN,107,814.659,0,1298
16128,APP1622-A,"Open - Apple Smart Keyboard Pro Keyboard Folio iPad 9.7 """,NaN,1.568.206,1.568.206,0,1298
17843,PAC2334,Synology DS718 + NAS Server | 10GB RAM,NaN,566.35,5.659.896,0,12175397
18152,KAN0034-A,"Open - Kanex USB-C Gigabit Ethernet Adapter MacBook 12 """,NaN,29.99,237.925,0,1298
18490,HTE0025,Hyper Pearl 1600mAh battery Mini USB Mirror and Comic Blond,NaN,24.99,22.99,1,1515
18612,OTT0200,OtterBox External Battery Power Pack 20000 mAHr,NaN,79.99,56.99,1,1515
18690,HOW0001-A,Open - Honeywell thermostat Lyric zonificador T6 Intelligent Wireless (cable),NaN,199.99,1.441.174,0,11905404

In [ ]:
products_df.loc[products_df['desc'].isna(), 'desc'] = products_df.loc[products_df['desc'].isna(), 'name']

In [ ]:
products_df.loc[products_df['desc'].isna(), :]

Empty DataFrame
Columns: [sku, name, desc, price, promo_price, in_stock, type]
Index: []

#### `price`

In [ ]:
products_df.price.isna().sum()

np.int64(46)

In [ ]:
print(f"The missing values in price are {(products_df.price.isna().value_counts(normalize=True).iloc[1] * 100).round(2)}% of all rows in the DataFrame")

The missing values in price are 0.43% of all rows in the DataFrame

Option 1: `.loc`

In [ ]:
products_df = products_df.loc[~products['price'].isna()]

Option 2: `.dropna()`

#### `type`

In [ ]:
products_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10534 entries, 0 to 19325
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sku          10534 non-null  object
 1   name         10534 non-null  object
 2   desc         10534 non-null  object
 3   price        10534 non-null  object
 4   promo_price  10534 non-null  object
 5   in_stock     10534 non-null  int64
 6   type         10484 non-null  object
dtypes: int64(1), object(6)
memory usage: 658.4+ KB

### Data types

We saw from looking at the output of `.info()` that both `price` and `promo_price` have been stored as objects and not as a numerical datatypes. We also saw while solving other problems that both columns have some prices with 3 decimal places and others with 2 decimal points - the latter will prevent us from converting the datatype to numerical, so first we must investigate and solve these problems.

#### `price`

First, let's see how many values are affected by the 2-decimal-dot problems or 3 decimal places.

In [ ]:
price_problems_number = products_df.loc[(products_df.price.str.contains(r"\d+\.\d+\.\d+"))|(products_df.price.str.contains(r"\d+\.\d{3,}")), :].shape[0]
price_problems_number

542

In [ ]:
print(f"The column price has in total {price_problems_number} wrong values. This is {round(((price_problems_number / products_df.shape[0]) * 100), 2)}% of the rows of the DataFrame")

The column price has in total 542 wrong values. This is 5.15% of the rows of the DataFrame

5.15% is a reasonable amount of our data. However, the price column will be important to understanding discounts, so I'd like it to be very trustworthy as we are basing business decisions on it. Therefore, we'll delete these rows

In [ ]:
products_df = products_df.loc[~((products_df.price.str.contains(r"\d+\.\d+\.\d+"))|(products_df.price.str.contains(r"\d+\.\d{3,}"))), :]

In [ ]:
products_df.sample(50)

,sku,name,desc,price,promo_price,in_stock,type
17905,PAC2280,Synology DS918 + NAS Server | 16GB | 32TB (4x8TB) WD Red,NAS server of the Plus Series for companies seeking high performance and the ability to scale memory and,2208.71,17.213.678,0,12175397
1687,PAC1800,Synology DS1815 Pack + | 16GB RAM | Seagate 16TB IronWolf,Nas + DS1815 RAM with capacity 16GB and 16TB (8x2TB) IronWolf Seagate Drives for Mac and PC,1974.49,17.927.457,0,12175397
14553,PAC1547,Enlargement Kit 2TB SSD Crucial MX300 + RAM + 8GB 1333MHz Datadoubler MacBook Pro 2011,SSD upgrade kit 2TB + 8GB 1333MHz RAM for MacBook Pro Early / Late2011 tools,796.52,6.405.849,0,1433
18523,TIL0010,Tile Combo Bluetooth Locators (Pack 4 units),Tile Combo pack 4 Bluetooth locators for your iPhone iPad and Apple Watch,74.99,579.905,1,11905404
1589,SPE0133,"Speck SeeThru MacBook Pro Retina Clear housing 15 ""transparent",Protective housing polycarbonate Macbooks Retina 15 inches.,49.9,399.905,0,13835403
12603,LUN0016,Flak lunatik Case iPhone 6 / 6S Silver,Multilayer Polycarbonate and silicone iPhone 6 / 6s,34.95,22.99,0,11865403
18823,KOO0007,Koogeek Homekit Smart Plug socket with Siri voice control,Koogeek plug with Apple HomeKit technology and Siri voice control for your home,34.99,289.899,0,11905404
10647,OTT0125,Otterbox iPad Mini Folio Symmetry 1/2/3 Black,Protective Case for iPad Mini Folio format 1/2/3 Black.,79.99,469.904,0,12635403
17592,SAN0188,SanDisk Ultra 64GB microSDXC card A1,Micro Memory Card with adapter read speed 100MB / s and video speed UHS U1,32.99,290.001,1,57445397
13001,IOT0020,iOttie Active Edge Support iPhone Indigo Blue Bicycle,Bike mount and bars up to 3 cm for iPhone,39.99,279.897,0,5720
16845,GLY0010,Glyph Atom SSD SSD RAID 1TB USB-C (3.1Gen2) Silver,1TB SSD with USB-C connection (compatible Thunderbolt 3 and USB 3.0) for Mac and PC,563.99,4.699.943,0,11935397
11084,SAN0113,SanDisk Ultra Flair Flash Drive 128GB USB 3.0,Pendrive USB 3.0 128GB USB Flash Drive Mac and PC.,49.99,500.008,0,11935397
848,OWC0092,Mac OWC Memory 8GB 1066MHz DDR3 DIMM,Mac Pro 8GB RAM (2009/2010).,56.99,499.899,1,1364
7992,APP1197,"Apple iMac 21.5 ""Core i5 31 GHz Retina display 4K | 8GB | 1TB",Desktop Apple iMac 21.5 inch i5 31 GHz Retina display 4K RAM 8GB 1TB (MK452Y / A).,1729,1305.59,0,1282
1530,PAC1817,Synology DS1515 + l 40TB (5x8TB) WD Red,Synology DS1815 + NAS hard drive WD 40TB Network for Mac and PC.,2936.94,22.629.626,0,12175397
13624,MUJ0025,Mujjo Leather Leather iPhone Case 8Plus / 7 Plus Champagne,ultrathin Case for iPhone vegetable tanned leather and 7 Plus 8 Plus,44.9,399.905,1,11865403
17965,NTE0123,"NewerTech NuGuard Snap-on Case MacBook Pro 15 ""Transparent",Protector for MacBook Pro 15 elegant and easy to install resistant inches,48.99,149.895,1,13835403
10792,MOX0027,Moxie Interior Case Simulation iPhone 6 / 6S,Cover for iPhone 6 / 6S.,19.99,149.895,0,11865403
14678,PAC1760,QNAP TS-231P NAS,NAS with 12TB capacity (2x6TB) WD Red hard drives for Mac and PC,726.59,6.301.789,0,12175397
16155,LGE0059,"24MP59G-P Monitor LG 24 ""FHD 1ms DP HDMI",238 inch monitor with 1ms response time HDMI and Display Port connection sRGB 99% for Mac and PC,199,1.889.996,0,1296
17002,PAC2174,QNAP TS-251A-4G NAS Server | 4GB RAM | 4TB (2x2TB) WD Red,NAS with 4GB of RAM and two hard disks 2TB (2x2TB) WD Network for Mac and PC,596.09,5.061.793,1,12175397
17646,IFX0081-A,iFixit piece connector Lightning and Audio Jack White iPhone 5s,Replacement parts Lightning connector and audio jack for iPhone 5s,24.95,143.926,0,1298
16244,PAC2120,"Apple iMac 27 ""Core i5 3.8GHz Retina 5K | 32GB | 512GB SSD",IMac desktop computer 27 inch Retina 5K RAM 32GB SSD 512GB PCle,3559,31.190.045,0,"5,74E+15"
13528,BEL0278,Air Belkin iPhone Case Protect SheerForce 8 Plus / 7 Plus Gold,Case technology against impact and wear resistant material and ultraviolet for iPhone 8/7 Plus,24.99,159.902,1,11865403
17556,AP20330,Like new - Apple iPad Case Silicone Case Mini 4 Charcoal Gray,Protective cover ultrafine silicone mini four cases.,69,349.896,0,12635403
2509,LEE0002-A,(Open) Leef iBridge PenDrive 32GB USB 2.0 Black Lightning,PenDrive 32GB USB 2.0 and Lightning for iPhone and iPad.,79.99,630.728,0,1298
12210,APP1583,"Apple MacBook Air 13 ""i5 16 Ghz | 8GB RAM | 256GB Flash",laptop MacBook Air 13 inch i5 16GHz 8GB RAM 256GB Flash (MJVG2Y / A),1349,1.165.593,0,1282
19001,SAT0068-A,Open - Satechi Hub Type-C 3 USB ports - one port Ethernet,Aluminum Hub Satechi refitted with 3 USB ports and 1 Ethernet port ideal for Mac,34.99,20.99,0,12585395
13763,IFX0156,"Battery iFixit MacBook Air 13 ""Early 2015 Mid 2012",Replacement Battery for MacBook Air 13-inch Mid 2012 to Early 2015,109.99,999.896,0,13005399
16162,LGE0056,"LG 34UC88-B Monitor 34 ""WQHD sRGB 99% Curved MaxxAudio",Monitor 34 inches WQHD 99% sRGB curved screen with adjustable height and tilt for Mac and PC,799,679,0,1296
11656,LGE0034,"LG 29UM68-P Monitor 29 ""IPS widescreen UXGA Ultra",29-inch IPS monitor: color accuracy sRGB split screen with 99% for Mac and PC,299,2.789.994,0,1296
1930,PAC0675,Samsung SSD 850 expansion kit EVO 1TB + 8GB RAM 1066Mhz + DataDoubler for MacBook and MacBook Pro 2008-2010,SSD expansion kit 1TB + 8GB RAM 1066Mhz + Datadoubler for MacBook and MacBook Pro Late 2008 to Mid 2010,605.96,4.465.844,1,1433
2545,NAT0024,Native Union Jump battery Ligtning Cable Gray / Blue,External Battery with USB Cable Lightning-800 mAh for iPhone iPad and iPod.,59.99,449.878,0,1515
13770,LAC0166-A,(Open) 4TB LaCie Rugged USB 3.0 Mini Mac and PC,Hard Disk 4TB portable wireless ultra-resistant USB 3.0 for Mac and PC.,219.99,1.943.075,0,1298
17070,TWS0116,Twelve South BookBook Case Black iPhone 7/8,Cover with vintage design book store card slot front cover and support for iPhone 7/8,59.99,569.898,1,11865403
296,DLK0015,D-Link DWA-131 Wireless N Nano USB Adapter,Dlink wireless Nano USB for Mac and PC.,14.99,128.998,0,1334
10801,TUC0240,Housing Sottile Tucano iPhone 6 / 6S Plus Transparent,Transparent Cover for iPhone 6 / 6S Plus,9.9,79.896,0,11865403
14912,PAC1877,expansion kit 525GB + SSD Crucial MX300 Datadoubler for Mac mini 2009 to 2010,SSD upgrade kit 525GB + Datadoubler for Mac mini 2009 to 2010 with tools,266.65,2.045.844,0,1433
17656,APP2529,Apple iPhone Leather Case Cover Skin 8/7 (PRODUCT) RED,ultrathin leather case and microfiber premium for iPhone 8/7,55,519.998,1,11865403
12155,SHE0037,SwitchEasy iPad Case White Pro CoverBuddy,Protective housing with Apple Pencil holder for iPad Pro 129 inches,39.99,299.003,0,12635403
11622,APP0957-A,"(Open) Apple MacBook Pro Retina 13 ""i7 3GHz | RAM 16GB | 128GB Flash",New MacBook Pro 13-inch Retina Display i7 3GHz 16GB RAM 128GB Flash (MF839Y / A).,2049,17.055.945,0,1298
15032,PIE0084,"Apple Power Cable Power Cable for iMac 215 ""(Mid 2011)",Power cord 215 inch iMac (Mid 2011) MC309LL / A MC813LL / A and MC814LL / A,19.99,199.904,0,1325
317,NTE0017,"NewerTech NuPower Battery MacBook 13 ""white",133 inch MacBook battery (White Model).,119.99,899.901,1,10142
11038,SAN0110,SanDisk Ultra Flair Flash Drive 16GB USB 3.0,USB 3.0 flash drive 16GB USB Flash Drive Mac and PC.,8.99,9,1,11935397
11939,APP1525,"Apple iPad Smart Cover Pro 97 ""Menta",Smart sleeve with different positions for cases Pro 97 inches.,59,549.897,0,12635403
11218,QNA0155,QNAP TS-453A | 4GB RAM Mac and PC Server NAS,4-bay NAS Server for Mac and PC.,529.99,456.99,1,12175397
11088,KIN0140,Kingston Memory Card microSDXC UHS Class 1 | 128GB,Memory card microSDXC UHS Class 1 128GB with transfer rates of 45MB / 10MB,69.99,502.803,0,57445397
1816,OWC0129,OWC SSD installation kit for iMac from 2007 or later,Installation Kit SSD iMac from 2007,35.99,329.894,0,14305406
3023,PAR0047,Parrot Drone White Airborne Cargo Mars,Cuadricóptero Drone Remote Control with Wi-Fi for iPhone iPad and iPod Touch.,99.9,949.898,0,11905404
11899,QDO0012,QDOS OptiGuard Titanium protector iPhone 6s Plus / Plus 6 full Rosa Gold,Crystal screen protector with metal finishing iPhone 6s Plus / 6 Plus,24.99,119.899,0,13555403

In [ ]:
products_df["price"] = pd.to_numeric(products_df["price"])

In [ ]:
products_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9992 entries, 0 to 19325
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sku          9992 non-null   object
 1   name         9992 non-null   object
 2   desc         9992 non-null   object
 3   price        9992 non-null   float64
 4   promo_price  9992 non-null   object
 5   in_stock     9992 non-null   int64
 6   type         9946 non-null   object
dtypes: float64(1), int64(1), object(5)
memory usage: 624.5+ KB

#### `promo_price`

Again, let's begin by seeing how many values are affected by the 2-decimal-dots problem, or the 3 decimal-places problem

In [ ]:
promo_problems_number = products_df.loc[(products_df.promo_price.str.contains(r"\d+\.\d+\.\d+"))|(products_df.promo_price.str.contains(r"\d+\.\d{3,}")), :].shape[0]
promo_problems_number

9232

In [ ]:
print(f"The column promo_price has in total {promo_problems_number} wrong values. This is {round(((promo_problems_number / products_df.shape[0]) * 100), 2)}% of the rows of the DataFrame")

The column promo_price has in total 9232 wrong values. This is 92.39% of the rows of the DataFrame

In [ ]:
promo_price_df = products_df.loc[(products_df.promo_price.str.contains(r"\d+\.\d+\.\d+"))|(products_df.promo_price.str.contains(r"\d+\.\d{3,}")), :]
promo_price_df.sample(50)

,sku,name,desc,price,promo_price,in_stock,type
18372,BEL0340,Belkin Cable HDMI High Speed ​​with Ethernet 5m,Belkin Cable High Speed ​​HDMI - Ethernet 5m for Mac,29.99,269.903,1,1325
2621,OWC0127,OWC Mercury Extreme Pro SSD 240GB 6GB,SSD 240GB SATA hard drive for Mac and PC III.,217.99,1.705.834,0,12215397
2972,LIF0083,Lifeproof nüüd Case Waterproof iPhone 6 Plus White,waterproof case for extreme conditions and iPhone 6 Plus.,99.99,249.865,0,11865403
17272,TUC0327,"Tucano tugo Medium Backpack 20L MacBook Pro 13 ""and 15"" / Retina / Air 13 ""Blue",Backpack 20 liter single compartment handles and pockets for MacBook Pro 13-inch and 15-inch / Retina / Air 13-inch,59.90,299.899,0,1392
11071,PAC1631,Pack QNAP TS-251 + | 2GB RAM | Seagate NAS 16TB,RAM nas TS-251 + 2 GB memory + 12TB (2x6TB) Hard Seagate IronWolf for Mac and PC,908.98,7.111.787,1,12175397
1373,APP0925,Apple Mac mini Core i7 3GHz | 16GB RAM | 256GB Flash,PC Mac mini Core i7 3GHz 16GB 1TB 256GB Flash (MGEQ2YP / A).,1579.00,15.000.043,0,1282
422,GRT0264,Griffin CinemaSeat Case for iPad mini / black Retina,IPad mini car cover neoprene support.,39.99,189.897,0,12635403
11871,MAC0125,Macally USB 3.0 to Gigabit Ethernet Adapter,Cable USB 3.0 Gigabit Ethernet adapter to connect 10/100 / 1000Mbps.,34.95,249.865,1,12585395
1475,SPH0012,Sphero Ollie Robot Blue,Smartoy of Sphero Ollie Robot remote control via Bluetooth App.,109.95,1.049.905,1,11905404
2462,FIF0009,FiftyThree Walnut Wood Pencil Pointer iPad,digital pointer with Bluetooth and multiplicity of stroke for iPad.,59.99,569.898,0,1229
2404,DEV0026,Devolo dLAN Starter Kit 650+ PLC,Kit 2 PLC network adapters 1-port Gigabit LAN.,99.99,999.944,0,1334
15320,LAC0147-A,Open - LaCie Rugged Mini 500GB 7200rpm USB 3.0,Hard disk portable wireless ultra-resistant USB 3.0 Mac and PC.,84.99,746.289,0,1298
13431,TUC0280,Tucano SOTTILE ultraslim 8/7 Transparent iPhone Case,transparent and flexible cover with 05mm thick for iPhone 8/7,7.90,69.902,1,11865403
14506,SYN0132-A,Open - Synology RT1900AC Wifi Router AC 1900,ac Wifi Wireless Router with Synology SRM interface,136.99,1.359.895,0,1298
15424,REP0356,Wi-Fi antenna repair iPad Air,Repair service including parts and labor for iPad Air,69.99,699.899,0,"1,44E+11"
13388,APP1678,Apple iPhone Silicone Case Cover 7 Blue Night,Ultrathin silicone case and microfiber premium for iPhone 7,39.00,359.902,0,11865403
17721,AP20363,Second hand - Apple Lightning to USB Cable 1m,Apple cable used and reviewed with USB connection to Lightning 1 m for iPhone iPad and iPod,25.00,139.997,0,1325
14958,KIN0156-A,Open - Kingston SSD Disk 240GB UV400,SSD HDD 240GB SATA 3.0 6Gb / s for Mac and PC,100.77,926.456,0,1298
2548,BOS0019,Bose SoundLink Color Red Speaker,Bluetooth wireless speaker for iPhone iPad and iPod.,139.00,1.349.876,0,5398
13774,APP1742,Watch Apple Nike + 38mm Silver Aluminum Case and Strap Smooth Silver Nike Sport / Voltio,Apple Watch 38 mm GPS processor with dual core Submersible 50mts strap exclusive Nike +,439.00,4.390.001,0,24885185
11817,APP1493,"Apple iPad Pro 9.7 ""256GB Wi-Fi Gray Space",9.7-inch Apple iPad Pro 256GB Wi-Fi Gray Space.,899.00,9.028.113,0,12141714
19152,LIF0119-A,Open - LifeProof Fre Case iPhone Waterproof 8 Plus Night Lite Black,Reconditioned LifeProof Case submersible in water and resistant to extreme conditions for iPhone 8 Plus or 7-Plus,89.99,549.722,0,11865403
3113,APP1176,Apple iPhone 6s 128GB Gold,New Free iPhone 6s 128GB.,639.00,6.259.996,0,24821716
2790,XDO0020,X-Doria Lux Apple Watch Strap 42mm Black Croc,Leather strap for easy installation Apple Watch.,30.99,268.995,1,2449
2386,PIE0061,Piece LCD iPad 2,LCD Replacement for iPad 2.,74.90,74.899,0,21535407
16235,PAC2144,"Apple iMac 27 ""Core i7 Retina 5K 42Ghz | 16GB | 2TB Fusion",IMac desktop computer 27 inch Retina 5K RAM 16GB 2TB Fusion,3079.00,28.470.045,0,"5,74E+15"
10943,FCM0039-4,Mac memory FCM 64GB (4x16GB) SO-DIMM DDR3 1867MHz,Mac memory FCM 64GB (4x16GB) DDR3 1867MHz SO-DIMM 27 inch iMac Retina 5K (Late 2015).,979.96,7.269.898,0,1364
16141,APP1532,"Apple iPad Silicone Cover Case Pro 97 ""Light Pink",Silicone light cover and soft touch for iPad Pro 97-inch.,79.00,499.899,0,12635403
14545,PAC1541,"Crucial SSD expansion kit MX300 525GB + 16GB 1066MHz RAM + Datadoubler for MacBook 13 ""Mid 2010 MacBook Pro 13"" Mid 2010",SSD upgrade kit 525GB + 8GB 1066MHz RAM for MacBook Late 2008 and Mid 2010 MacBook Pro 2008 to 2010 with tools,466.63,3.985.849,0,1433
12642,SPE0177,"Speck SeeThru Case Macbook Air 13 ""Blue Calypso",Protective housing MacBook Air 13 inches,49.90,399.905,0,13835403
18356,BEL0348,Belkin USB 2.0 Printer Cable A to B 1.8m,USB 2.0 cable type A male B 18m.,5.99,59.895,0,1325
12306,TUC0266,Case Filo Tucano iPhone 5 / 5S / SE Black,Case with Magnetic Closure for iPhone 5 5s and SE,19.90,169.896,1,5403
16867,APP2159,Apple Pencil Case brown Topo,Carrying case with leather material for Apple Pencil,35.00,350.005,1,1229
16953,SAM0109-A,Open - Samsung EVO SSD 750 500 GB,SSD Hard Drive SATA 6 Gb / s 25-inch NAND technology for Mac and PC.,149.99,1.445.956,0,1298
1337,SPE0129,Candishell Speck Case iPhone 6 Green / Yellow,ultra resistant iPhone 6. Housing,24.99,219.857,0,11865403
12231,APP1563,Silicone Case Apple Case iPhone 6 / 6S Plus Rosa Claro,Ultrathin silicone case and microfiber premium for iPhone 6 Plus / 6s Plus,45.00,419.894,0,11865403
15265,PIE0088,Extension Cable for Apple 45W MagSafe 65W 85W,MagSafe and extension cable for Magsafe2 180m,25.00,18.991,1,1325
15137,GTE0092,G-Technology G-SPEED XL 18TB Studio Thunderbolt 2 EV Series,Hardware RAID external storage with 18TB of capacity and Thunderbolt 2 Connection for Mac and PC,3290.54,28.077.941,0,11935397
13430,SAM0116,"S22F350FHU Samsung Monitor 22 ""Full HD LED HDMI Black",22 Eco Monitor mode for energy saving super slim design and base circulate for Mac and PC,129.99,1.069.894,0,1296
14714,MAC0116-A,"Open - Macally USB 3.0 External Enclosure 2.5 ""SATA Plata",Reconditioned aluminum outer casing 2.5 HDD USB 3.0 for Mac and PC inches.,29.95,120.653,0,1298
11996,BEL0192,MIXIT Belkin Car Charger Premium Dark Gray,Metallic car charger for iPad iPhone and iPad.,14.99,129.906,1,13615399
16133,AKI0027,"Akitio SK-2520 C-U3.1 USB External Box 25 """,RAID outer box 2 drive bays 25 inch USB-C (10 Gbps) Mac and PC connection,177.00,1.399.897,0,11935397
11885,MAC0114,"Macally Folio case iPad Case Pro 129 ""Black",Folder Case for iPad type polyurethane Pro 129 inches.,34.95,299.003,0,12635403
15304,WAC0230,Wacom Intuos Pen & Touch 3D Creative Medium Black,graphics tablet with ExpressKeys keys multi pencil precision and free 3D software for Mac and PC,199.99,1.769.903,0,1405
17692,LAC0240,6big Lacie Hard Drive 12TB RAID Thunderbolt 3 USB-C,12TB hard drive bays with RAID 6 5 two ports Thunderbolt 3 (40Gb / s) and 5 years warranty for Mac and PC,1999.00,17.699.941,0,11935397
18237,BEL0308,Belkin Audio Adapter (Lightning Charge + Jack Port) Rockstar,Audio Adapter 35 mm + loaded with Lightning connection for iPad and iPhone,34.99,349.932,1,14365395
16511,APP2084,"Apple MacBook Pro 13 ""Core i5 with Touch Bar 31Ghz | 8GB RAM | 256GB PCIe SSD Plata",New MacBook Pro 13 inch Touch Bar 31 GHz Core i5 with 8GB of RAM and 256GB PCIe SSD,2005.59,18.850.046,0,"1,02E+12"
482,OWC0060,Mac OWC Memory 2GB 667MHz DDR2 SO-DIMM,2GB RAM Mac mini and iMac (2006/07) MacBook Pro (2006/07/08).,23.99,209.899,1,1364
17301,OWC0110-A,"Open - OWC Multi-Mount Kit Mac Pro 2009/2010 Adapter 2.5 ""to 3.5""",SSD or HDD Adapter 2.5 to 3.5 and 525 for Mac Pro 2009/2012,35.99,389.397,0,1298
15639,WAC0236,Wacom Bamboo Pen Digital pen,12g pointer 512 pressure levels for Bamboo MTE-450,34.99,349.896,1,1229

So we were correct, over 90% of the data in this column is corrupt. There's no point deleting all of these rows, then we would barely have a products table. Instead, as it's only this column that appears to be very untrustworthy, we will delete the column.

In [ ]:
products_cl = products_df.drop(columns=["promo_price"])

In [ ]:
products_cl.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9992 entries, 0 to 19325
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   sku       9992 non-null   object
 1   name      9992 non-null   object
 2   desc      9992 non-null   object
 3   price     9992 non-null   float64
 4   in_stock  9992 non-null   int64
 5   type      9946 non-null   object
dtypes: float64(1), int64(1), object(4)
memory usage: 546.4+ KB

In [ ]:
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# Define the project folder
output_folder = "/content/drive/MyDrive/Project 2 (Discounts) Datasets"

# Save cleaned DataFrames to Google Drive
orders_df.to_csv(f"{output_folder}/orders_cl.csv", index=False)
orderlines_df.to_csv(f"{output_folder}/orderlines_cl.csv", index=False)
products_cl.to_csv(f"{output_folder}/products_cl.csv", index=False)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).